<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <InfoBox statusType="tip" statusName="旅遊總覽">
      <p>
        這邊會記錄旅遊上經歷的大小事
        <br />
        可以在下面的系列文章看看有沒有能幫上忙的
      </p>
    </InfoBox>
    <p><a href="/trip/hokkaido_precaution">2023北海道</a></p>
  </article>
</Post>
