<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';

  import Youtube from '$lib/components/youtube.svelte';
  import Custom from '$custom/custom.svelte';
  import Spotify from '$lib/components/spotify.svelte';
  import Folder from '$lib/components/folder.svelte';

  let configFolder = [
    { name: 'QWER.config.js', icon: 'i-vscode-icons-file-type-typescript-official' },
    { name: 'site.ts', icon: 'i-bxs-file-js' },
  ];
</script>

<Post>
  <article slot="post_content">
    <InfoBox statusType="tip" statusName="起因">
      <p>
        在YT蝦晃的時候，被這一小段
        <a href="https://www.youtube.com/watch?v=gidpDOWNLpI" rel="external">插入曲</a>
        給吸引到
      </p>
    </InfoBox>
    <h2 id="original-video"><a href="#original-video">Original Video</a></h2>
    <p><Video mp4="/music_coloring/algernon/algernon.mp4" id="アルジャーノン" /></p>
    <h2 id="arujnon"><a href="#arujnon">アルジャーノン(阿爾吉儂)</a></h2>
    <p>
      アルジャーノン(阿爾吉儂) 是為電視劇『夕暮れに、手をつなぐ』(意思是夕暮時分牽起手)
      所做的主題曲，而歌曲名的靈感取至美國作家丹尼爾·凱斯著作《獻給阿爾吉儂的花束》，而正巧也有在2015年被翻拍成日劇，由帥到掉渣的山下智久擔當男主角
      <br />
      <br />
    </p>
    <p>
      作品中的阿爾吉儂其實是一隻被注射實驗藥物而變聰明的老鼠，而主角則是一位天生的智能障礙者，因緣際會下被選中為人體實驗品而被注射相同的藥物，這也使得他一夕之間成為智商超群的天才。
      <br />
    </p>
    <p>
      不過心靈層面趕不上智商躍升的後果就是他比以前更不信任他人，此時他也發現藥物的副作用...
      除了智商退化外甚至不知還剩幾日可活，而這本《獻給阿爾吉儂的花束》其實本身就是一個實驗記錄，刻畫著從一開始的錯字連篇，一天天演變成複雜艱深的詞彙，歷經錯綜複雜的情緒糾結最後再退回當初童稚的語氣...
      <br />
    </p>
    <h2 id="dian3-ping2"><a href="#dian3-ping2">點評</a></h2>
    <p>n-bana對這首歌的評價如下</p>
    <div class="code-block  ">
      <CodeCopy>
        <pre><code>{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">箱の中に迷路がある。</div></div><div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">途方もなく複雑に入り組んだ道を貴方は歩いていく。</div></div><div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content"></div></div><div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">壁の向こう側に何かがあると信じて止まらず</div></div><div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">時折道に迷いながらもただ出口へと進み続ける。</div></div><div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">その姿が僕には少し眩しい。</div></div><div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content"></div></div><div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">そういう曲です。</div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <p>
      意思大概是
      <br />
      盒子裡面有一個迷宮。
      <br />
      你走在一條極其複雜和錯綜複雜的道路上。
      <br />
      我無法停止相信牆的另一邊有東西
      <br />
      儘管我有時會迷路，但我只是一直往出口走。
      <br />
      就是那種歌。
      <br />
    </p>
    <h2 id="xiao3-jie2"><a href="#xiao3-jie2">小結</a></h2>
    <p>
      作者在《獻給阿爾吉儂的花束》一書中，拋出了一個從未有人釐清的問題：智慧與幸福能否兼得？
      <br />
      到底是追求平凡的幸福還是承擔擁有智慧後的責任，就像n-buna說的，我們都在這錯綜複雜的情緒中不斷糾結著。
      <br />
      不過回頭看看，說不定就會發現愛你的人
      <br />
      所以不管有甚麼困難，平靜地等待吧，慢慢的改變，就像那緩緩膨脹的麵包
      <br />
      這就是為甚麼我們能繼續向前邁進而不用擔心這長長的迷宮
      <br />
    </p>
    <Spotify id="0L1E2JmrZk6QU9261PtJWQ" />
  </article>
</Post>
